# Generated by Django 4.0.4 on 2022-06-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT INTO store_collection (title)
            VALUES ('collection1')
            ''',
            '''
            DELETE FROM store_collection
            WHERE title='collection1'
            '''
        )
    ]
