# Generated by Django 4.0.4 on 2022-06-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220606_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='fearured_product',
            new_name='featured_product',
        ),
    ]
