# Generated by Django 4.0.4 on 2022-06-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_fearured_product_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
